// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axuihnyckjwqwodkrglg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4dWlobnlja2p3cXdvZGtyZ2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MjA0MzMsImV4cCI6MjA1ODk5NjQzM30.5-Wg9hOgh8KRiXHELHihrTp9duQzMe6jYxMv0qrVPeA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);